### ISSUE TITLE
Use large image preview for podcast episodes

### ISSUE THREAD

**Issue by dergigi** [seetee-io/seetee-io#64]
The preview looks nice, but it is small.

<img width="565" alt="Screenshot 2022-02-01 at 21 27 17" src="https://user-images.githubusercontent.com/109058/152045755-7ecf6c45-7455-4e52-b418-d4a7d0c9958c.png">

We should use the `summary_large_image` tag for twitter cards to get the large preview.

The [twitter card validator](https://cards-dev.twitter.com/validator) is a useful tool to check this.

**Comment by dnlggr** [comment]
For the blog, where we have large cover images I agree completely, for the podcast episodes, where we only have square episode thumbnails, I feel like the smaller is a better fit. Cf. below:

![Screenshot 2022-02-02 at 15 37 10](https://user-images.githubusercontent.com/10026790/152174733-5a99194b-afc5-4e55-b01c-8496efa7d169.png)

**Comment by dergigi** [comment]
Ah, damn auto-crop! Yeah I agree that sucks. Let me sleep on it, there might be a way to do this properly.

**Comment by dergigi** [comment]
Let's leave it as is for now, since we would've to add custom images for the large cards to deal with the auto-crop. Closing issue.
